#!/usr/bin/env python3
"""
update_routes.py — Mapit Heatmap Data Updater
==============================================
Run this script after adding new route JSON files to the routes/ folder.
It scans all *.json files, merges them, and regenerates routes/routes.js.

Usage:
    python3 update_routes.py

To add new routes from a Mapit HAR export:
    python3 update_routes.py --from-har path/to/export.har
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROUTES_DIR = Path(__file__).parent / 'routes'


def load_existing_routes():
    routes = []
    for f in sorted(ROUTES_DIR.glob('*.json')):
        with open(f) as fp:
            routes.append(json.load(fp))
    return routes


def import_from_har(har_path):
    print(f"Importing routes from {har_path}...")
    with open(har_path) as f:
        har = json.load(f)

    routes_raw = None
    for e in har['log']['entries']:
        if 'geo.prod.mapit.me/v1/routes' in e['request']['url'] and e['request']['method'] == 'GET':
            routes_raw = json.loads(e['response']['content']['text'])['data']
            break

    if not routes_raw:
        print("ERROR: No routes data found in HAR file.")
        sys.exit(1)

    existing_ids = {f.stem.split('_', 1)[1] for f in ROUTES_DIR.glob('*.json')}
    new_count = 0

    for r in routes_raw:
        if r['id'] in existing_ids:
            continue  # already saved

        started = datetime.fromisoformat(r['startedAt'].replace('Z', '+00:00'))
        ended   = datetime.fromisoformat(r['endedAt'].replace('Z', '+00:00'))
        date_str = r['startedAt'][:10]
        day_of_week = started.isoweekday() - 1  # 0=Mon, 6=Sun

        coords = []
        for feat in r['geoJSON']['features']:
            if feat['geometry']['type'] == 'LineString':
                for c in feat['geometry']['coordinates']:
                    coords.append([round(c[1], 6), round(c[0], 6)])

        if not coords:
            continue

        route_obj = {
            'id':        r['id'],
            'date':      date_str,
            'dayOfWeek': day_of_week,
            'distance':  round(r.get('distance', 0) / 1000, 3),
            'duration':  round((ended - started).seconds / 60, 1),
            'maxSpeed':  r.get('maxSpeed', None),
            'avgSpeed':  r.get('avgSpeed', None),
            'coords':    coords
        }

        fname = f"{date_str}_{r['id']}.json"
        with open(ROUTES_DIR / fname, 'w') as fout:
            json.dump(route_obj, fout, separators=(',', ':'))
        new_count += 1

    print(f"Added {new_count} new routes ({len(routes_raw) - new_count} already existed)")


def generate_routes_js(routes):
    routes_sorted = sorted(routes, key=lambda x: x['date'])
    min_date = routes_sorted[0]['date']
    max_date = routes_sorted[-1]['date']

    content = (
        f"// Generated by update_routes.py — {len(routes_sorted)} routes "
        f"({min_date} → {max_date})\n"
        f"window.ROUTES_DATA = {json.dumps(routes_sorted, separators=(',', ':'))};\n"
    )

    out_path = ROUTES_DIR / 'routes.js'
    with open(out_path, 'w') as f:
        f.write(content)

    print(f"✓ routes.js updated: {len(routes_sorted)} routes, {len(content):,} bytes")
    print(f"  Date range: {min_date} → {max_date}")


if __name__ == '__main__':
    ROUTES_DIR.mkdir(exist_ok=True)

    if '--from-har' in sys.argv:
        idx = sys.argv.index('--from-har')
        har_path = sys.argv[idx + 1]
        import_from_har(har_path)

    routes = load_existing_routes()
    if not routes:
        print("No route JSON files found in routes/")
        sys.exit(1)

    generate_routes_js(routes)
